# This is a basic workflow to help you get started with Actions

name: Test GitHub Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Person'
        required: false
        default: 'Ahmed'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Terraform init azurerm backend
      # You may pin to the exact commit or the version.
      # uses: ahmedig/terraform-azurerm-backend@de5e6845254df2a464eaa31891bab20c2b4977e0
        uses: ahmedig/terraform-azurerm-backend@${GITHUB_SHA}
        with:
          # Azure Credentials in JSON format
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          # State file location - resource group name
          resource_group_name: ghaction-rg
          # State file location - container name
          container_name: ghaction
          # State file location - storage account name
          storage_account_name: ghaction
          tf_working_directory: tests